appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Pu8hnQVU3loxjJBYqzJjSqk5jNwiH7DtI6fv1TKmiJdM00MuS5vJHRkpHVNLGyxqH6WS1pBtD4sjPDIv0EC7I1AREdgWRwogxh42l1R9pK/216Jy08CVKektAf7yfrDxP0hszBddgVRgIAjEReJ5PPxUHXGzYFOfdktrHLkL5D7wXoslCRpI+rKGI1gi53B4YDBf2hzyqFgKDum1k6OClgZydZwebEo0Qf5ZzuzNLxoT7a0U7Fpg4A/lYDZa3NNoBBEmw7AM2q5Qbo3EI8hogi6xLo5TMLCMln/r0OL8FEARCN2ldU1mAx+zt6zZ4IFizYSxhzOExezIjTxzqb2T7WJPn+x+wvloCYH79oQLARbOVPei2/zxBKAO3vyMTFsEZ4Rcs86YelBOOh1+JJTPFSFg0M74G7eRprBLCUIN1NWb3EzbLRKy2ucDq5VUlzO5qdvqdx8QRbZsb1nHtRbb47elfqVYNzR5wmV1TzCw55K3J8MOe4HlC7oHj6rkBuSt2UqoyzT6t467JGSg8kyHSUh1+npfTRV7DOegxdPfR+lzsKYg/GJ86k8/4ODpei45vjLnjmuQj+0vEmrAHM3IePZbXlQB1C0kEnZ3dHcVHHtKU0+9uwsji9WCOpEAvGqNBq2M6TY7zVs7b5tunpkLaBaDgNIJwNEbV/9fdvviEbU=}
conda_forge_output_validation: true
