travis:
  secure:
    BINSTAR_TOKEN: BhnntS39mKk7Kt+tYWOsTwrEV9ewfU5ZWHHnJcC6Qc6pM8F35p25l4TLmKV40biFJmYWd08Be1UdqN2HvBxKJzyxmPbsSEMGzhj+AjeB5GoST/ToE9qrJObCDN0Cwc26LQyA1Xfi/v7rjOeuc7NqKUmPs3grqmvEjrPKZJSYGwwqmNFYqmXVol9b1QuwuhTBPMO1Fey3r6pGD4EmU1vuBgZbOEaEH6xN/48VtXls8qS88nlurl2IwkEOQ6TX1TSMYfDgQXT39F0uFH0lhZy1cNzN/YsTJ6XP7grulLPJVpbBkZzbmQah4w3TOz6HggHsZ861i2xGIt6xOPWaCsDmLz/Tsa0ioHbMEIdMra/XGSq8H+T0FGS+nmr9NLl3k0vQu52zn1yPTWkAIbN06uEIy75YjNfk+wpAarIYS5ZxIUagoA9gvincXbVzeFubgqlqz+xOmAOweYw+HLRIW3OnaOSWfj/tBRp5lnjATSl/RJ9QxIlmvej9bXfcPOcwm1wLZNEGp5kbdomELBXxJXK98G87tUiwnXWGQftgu3xMnMVtUCSVJSNSA6ZUg+iWNFbxthXHfTM0MV3bw028GkkpoAPDthnhfIcLv95B5Xm4NYNXZMHejVP86dwKd3JNCRG9jM5CUCS2KSgQGKlgQ0Y1XTC82QW1eBIKq+LXGKuZBDI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
