travis:
  secure:
    BINSTAR_TOKEN: I62u6gUf0Kgz6zYm8am/mfkD3uNA/OdSJ1eS+axrBWqrGbdkzuO5phiKEHj8UzwqR8jlZ568b8BruezAWevHBwTZKqJOHLI8YKSIkcPA08TuoQkHl6l+2mQYg/+5sXCfUVqFl3J1py7vFS6p+YbVTHJjq8XqGuiIs9/gu/84lIPcB1gSqvgbCR07tawb/3crIHjMSKtiJxQvE0EU1aoMaQxzaEWpAaLi0biY1TSiqfqnngx46eXl1JoTljheAcH7z6Vdc/bzWEX11CIgpb5MhRH6PSDdt1fghYdqz/6HUE5qJQS0Ror0Ly0Rd+YEkO0eJlqCs/NOjDMWzgTTGGmzj/C8OY2wgIRee/oG3y/7sazgpIbP6iSYmBZk7EnrG/1xIQL1LqDSlefTcRsEm/JsmHdfx5Fp63ooyyPrlfYAjp6i6xSBcUTVD7lxbDO9ELzu05SQm2vmA3JcPGWS0YZkE7o0qzkLMBF/CPAijr8+7CDUwuSLy0iWKNpUSLQcZyXkoJGZGmKTAdZUJKcChniWs0XtyNJ6aVWCEiFT7ze73mbqx35vdxd0o4WnRuU5oyzZX61clxlFsKGqR8iuj/LUjzAt5RdVqddDFMRPom3kLfifjzPaNwU4t3zCSrwzo5FJqE0AdFXBx06nClccjdCgmYYfByRLESLNwXhOM4aHZWk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
